name: "Test and Deploy"
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test_and_gen_doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up node environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install all dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build Docs
        run: npm run doc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
